name: guideapp_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.5
  get: 4.6.5
  dio: 4.0.6
  mrx_charts: 0.1.3
  flutter_typeahead: 4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  flutter_launcher_icons: 0.10.0
  flutter_native_splash: 2.2.9

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#0E0E0E"
  image: "assets/images/splash/splash.png"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/icons/icon_app.png"
  image_path_ios: "assets/icons/icon_app.png"
  remove_alpha_ios: true